# Generated by Django 4.2.30 on 2026-06-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('call', 'เรียกพนักงาน'), ('bill', 'เรียกเก็บเงิน')], max_length=10, verbose_name='ประเภท')),
                ('status', models.CharField(choices=[('pending', 'รอการจัดการ'), ('handled', 'จัดการแล้ว')], db_index=True, default='pending', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลาที่สร้าง')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่จัดการ')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_notifications', to='staff.staff', verbose_name='พนักงานที่จัดการ')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tables.restauranttable', verbose_name='โต๊ะ')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือนทั้งหมด',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_notif_status_created'), models.Index(fields=['created_at'], name='idx_notification_created')],
            },
        ),
    ]
