# Generated by Django 4.2.30 on 2026-06-28 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='เช่น A1, B2, 01, VIP1', max_length=20, unique=True, verbose_name='หมายเลขโต๊ะ')),
                ('seats', models.PositiveSmallIntegerField(default=4, verbose_name='จำนวนที่นั่ง')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID สำหรับสร้าง QR Code, auto-generated', unique=True, verbose_name='QR Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'โต๊ะอาหาร',
                'verbose_name_plural': 'โต๊ะอาหารทั้งหมด',
                'ordering': ['number'],
            },
        ),
    ]
