# Generated by Django 4.2.30 on 2026-06-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 ดาว', verbose_name='คะแนนความพึงพอใจ')),
                ('suggestions', models.TextField(blank=True, verbose_name='ข้อเสนอแนะเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='tables.restauranttable', verbose_name='โต๊ะ')),
            ],
            options={
                'verbose_name': 'ข้อเสนอแนะ',
                'verbose_name_plural': 'ข้อเสนอแนะทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
