# Generated by Django 4.2.30 on 2026-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_customerfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranttable',
            options={'ordering': ['sort_order', 'number'], 'verbose_name': 'โต๊ะอาหาร', 'verbose_name_plural': 'โต๊ะอาหารทั้งหมด'},
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับจัดเรียง'),
        ),
    ]
