# Generated by Django 4.2.30 on 2026-06-28 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='รหัสพนักงานที่ unique เช่น EMP001', max_length=20, unique=True, verbose_name='รหัสพนักงาน')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อพนักงาน')),
                ('pin_hash', models.CharField(help_text='เก็บ PIN ในรูปแบบ hash โดยใช้ make_password()', max_length=255, verbose_name='PIN (hashed)')),
                ('avatar_emoji', models.CharField(default='👤', max_length=10, verbose_name='Avatar Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงานทั้งหมด',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StaffDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(help_text='Firebase Cloud Messaging token ของ device', verbose_name='FCM Token')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='staff.staff', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'อุปกรณ์พนักงาน',
                'verbose_name_plural': 'อุปกรณ์พนักงานทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาเข้างาน')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='เวลาออกงาน')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_logs', to='staff.staff', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'บันทึกกะงาน',
                'verbose_name_plural': 'บันทึกกะงานทั้งหมด',
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['staff', '-clock_in'], name='staff_shift_staff_i_a326c3_idx'), models.Index(fields=['clock_out'], name='staff_shift_clock_o_9fb432_idx')],
            },
        ),
    ]
