# Generated by Django 4.2.30 on 2026-06-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('staff', 'พนักงานทั่วไป')], default='staff', max_length=20, verbose_name='ระดับสิทธิ์'),
        ),
    ]
