# Generated by Django 4.2.30 on 2026-06-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='pin_hash',
        ),
        migrations.AddField(
            model_name='staff',
            name='password_hash',
            field=models.CharField(default='', help_text='เก็บ Password ในรูปแบบ hash โดยใช้ make_password()', max_length=255, verbose_name='Password (hashed)'),
            preserve_default=False,
        ),
    ]
